[tool]
[tool.poetry]
authors = ["Jeremy A Gray <jeremy.a.gray@gmail.com>"]
description = "FCC DA Time Series Visualizer Project"
name = "fcc-da-time-series-visualizer"
version = "0.0.1"
[tool.poetry.dependencies]
pandas = "*"
python = "^3.7"
seaborn = "*"
